### ISSUE TITLE
表格读取出来的时间和数据库存储的不一致

### ISSUE THREAD

**Issue by QiuYiBin** [quarkcms/quark-admin#10]
数据库存储的是2020-12-12 19:17:19，表格读取出来的2020-12-12 11:17:19

https://learnku.com/laravel/t/48104

**Comment by tangtanglove** [comment]
如果是laravel6的话，设置好时区就没问题；laravel7会有这个问题

**Comment by tangtanglove** [comment]
有没有什么好的建议？

**Comment by QiuYiBin** [comment]
> 如果是laravel6的话，设置好时区就没问题；laravel7会有这个问题
好的，我现在使用的是Laravel 8的版本
