### ISSUE TITLE
老大能否补充个自定义组件的教程

### ISSUE THREAD

**Issue by jiangslee** [quarkcms/quark-admin#16]
同标题，不知道怎么入手，希望老大补充一下自定义组件的教程。

**Comment by tangtanglove** [comment]
如果需要自定义页面的话，可以自己编译quark ui

**Comment by tangtanglove** [comment]
1.0版本可能麻烦一点，2.0重构版就简单了

**Comment by jiangslee** [comment]
> 1.0版本可能麻烦一点，2.0重构版就简单了

好的，项目很赞，期待2.0
