### ISSUE TITLE
【感谢大佬】问一下  account/settings 页面如何自定义出来的？

### ISSUE THREAD

**Issue by EchoDzg** [quarkcms/quark-admin#18]
前置说明：
from 组件 跟table 组件 很多情况下 不太满足业务。想自己定义个界面 用 文档里的  like 跳转 不能直接 用blade模板引擎。
查阅了几遍文档  说明如下：

查阅文档：
```
当 渲染组件 表单项选择 引擎组件 的时候，你需要填写返回数据的api接口，例如：admin/admin/index，这里不用加api这个前缀；当 渲染组件 选择 无组件 的时候，你需要填写QuarkUI前端定义的路由，例如：/account

```
疑惑点：
但是没有 写道如何制作 的 account/settings界面，直接用view方法的话会空白，得把前端代码包拉取回来自己在编译成组件才行？

**Comment by tangtanglove** [comment]
嗯嗯，是的，需要自己写前端的组件然后编译

**Comment by tangtanglove** [comment]
内置的组件暂时只能满足通用情况下业务需求，如果业务比较复杂就只能自己写前端组件了

**Comment by tangtanglove** [comment]
新的版本正在参考百度的[amis](https://baidu.gitee.io/amis/zh-CN/docs/index)，重新架构以简化这些问题。

**Comment by EchoDzg** [comment]
非常感谢大佬百忙之中的热心回答。 最后提问个 现有 组件的问题。
使用组件：table  组件-> 数据筛选

使用代码：
 $search->equal('file_course_id', '课程')->select(Post::selectlist())
 ->placeholder('选择课程');

Post::selectlist() 代表一组 数据。 我查阅了很多文档，没发现到如何默认 选中一个  筛选条件。
form 组件里可以default的方法指定一个value即可。但是 table 里的筛选组件 selelct 下拉框 没找到给默认值的方法。

**Comment by tangtanglove** [comment]
嗯，现在这个确实没有，,也不难，欢迎提个PR。

**Comment by EchoDzg** [comment]
感谢大佬，单纯上面这个问题 ，在 Quark  Ui 的项目 里有个  QueryFilter.tsx 文件  ，150行  左右 加了一行 ：
initialValue={item.defaultValue} 就支持这个功能了。 
Quark  Ui  项目回头我提个代码上去。

**Comment by EchoDzg** [comment]
大佬参考下 这个文档：https://www.yuque.com/smallruraldog/laravel-vue-admin/bvuqfn
能否百忙之中 抽空撸个 跟上面一样 的文档说明。  让小弟们也协助进来 制作更多的组件。

**Comment by tangtanglove** [comment]
QuarkUI2.0引入了qiankun微前端，届时将解决引入其他组件的问题，你有兴趣可以看看develop分支。
