### ISSUE TITLE
同步权限和全部删除bug

### ISSUE THREAD

**Issue by w362201889** [quarkcms/quark-admin#19]
### 环境:宝塔(apache2.4+php7.3.9+mysql5.6)

**bug1**:后台管理员下面有个权限列表,点进去有个同步权限,点击同步权限没有反应
临时解决办法vendor>quarkcms>src>http>controllers>permissionController.php
大约38行修改为`$action->button('同步权限')->type('primary')->api('admin/permission/sync?');`
在sync后面添加了一个问号

**bug2**:后台附件空间下面有个文件管理,点进去有个全部删除,点击全部删除没有反应
临时解决办法vendor>quarkcms>src>http>controllers>FileController.php
大约63行修改为`$action->a('批量删除')->withConfirm('确认要删除吗？','删除后数据将无法恢复，请谨慎操作！')->model()->whereIn('id','{ids}') ->delete(['status'=>0]);`
推测原因:delete()需要传值

**bug3**:后台附件空间下面有个图片管理,点进去有个全部删除,点击全部删除没有反应
临时解决办法vendor>quarkcms>src>http>controllers>PictureController.php
大约63行修改为`$action->a('批量删除')->withConfirm('确认要删除吗？','删除后数据将无法恢复，请谨慎操作！')->model()->whereIn('id','{ids}') ->delete(['status'=>0]);`
推测原因:delete()需要传值(同上)

**Comment by tangtanglove** [comment]
laravel是哪个版本？

**Comment by w362201889** [comment]
Laravel Framework 6.20.30

**Comment by w362201889** [comment]
quarkcms的话是Laravel Framework 7.30.3
quark是Laravel Framework 6.20.30
这两个安装了两个测试网站,在对比着学习
quark也是遇到了上面那几个问题

**Comment by tangtanglove** [comment]
方便在Chrome调试工具里看一下返回数据吗？应该没问题的

**Comment by w362201889** [comment]
umi.b88602b4.js:1 Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at i (umi.b88602b4.js:1)
    at umi.b88602b4.js:1
    at u (umi.b88602b4.js:1)
    at Generator._invoke (umi.b88602b4.js:1)
    at Generator.forEach.e.<computed> [as next] (umi.b88602b4.js:1)
    at r (umi.b88602b4.js:1)
    at c (umi.b88602b4.js:1)
    at umi.b88602b4.js:1
    at new Promise (<anonymous>)
    at umi.b88602b4.js:1 #

**Comment by w362201889** [comment]
这是同步权限的,我试着添加?,同步权限访问的链接会变成url?&,也就是这里一定会有一个&,不清楚是什么原因,
全部删除那里我看了实现方法,删除的方法里必须传值id

**Comment by tangtanglove** [comment]
quark-admin是最新版本吗？

**Comment by w362201889** [comment]
应该是的,昨天上午10:50从github下载的

**Comment by tangtanglove** [comment]
嗯嗯，你重新编译一下quark-ui，替换一下试试。

**Comment by w362201889** [comment]
额,咋编译,我没用过这个ui,quark-ui不是前端的插件吗,我看着您把他这拆出来了呀,不是有个quark-admin,quark-cms,quark-ui三个

**Comment by tangtanglove** [comment]
下午有时间我编译一下，发布个版本吧

**Comment by w362201889** [comment]
好的,辛苦了

**Comment by tangtanglove** [comment]
更新到v1.1.30版本试一下
