### ISSUE TITLE
php artisan quark:install 报错

### ISSUE THREAD

**Issue by ECMAScript6** [quarkcms/quark-admin#22]
root@ubuntu:/home/leishaojun/micf# php artisan quark:install

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:692
    688▕         // If an exception occurs when attempting to run a query, we'll format the error
    689▕         // message to include the bindings with SQL, which will make this exception a
    690▕         // lot more helpful to the developer instead of just the database's errors.
    691▕         catch (Exception $e) {
  ➜ 692▕             throw new QueryException(
    693▕                 $query, $this->prepareBindings($bindings), $e
    694▕             );
    695▕         }
    696▕     }

      +45 vendor frames 
  46  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by tangtanglove** [comment]
数据库的配置没有设置
