### ISSUE TITLE
安装后访问报错404

### ISSUE THREAD

**Issue by Klein-s** [quarkcms/quark-admin#25]
按照文档安装步骤安装完成后，访问 admin 页面报错 404， laravel默认页面是正常的
请求错误 404: http://quark.test/api/admin/login?
发出的请求针对的是不存在的记录，服务器没有进行操作。
![image](https://user-images.githubusercontent.com/63279751/145505959-e99da5d3-382f-4df0-9df5-941ee931eab4.png)

**Comment by tangtanglove** [comment]
需要设置好伪静态

**Comment by stolendust** [comment]
不好意思，我也遇到了同样的问题， 但是网站已经为lavarel设置了伪静态（如下），请问您说的伪静态是指什么呢
location / { 
	try_files $uri $uri/ /index.php?$query_string; 
}
