### ISSUE TITLE
列表关联表信息怎么做

### ISSUE THREAD

**Issue by tuowt** [quarkcms/quark-admin#27]
大佬咨询问题

列表：关联表信息怎么获取

怎么设置避免 N + 1

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/60868863/146743662-5d0a259c-6cf1-4051-a32b-4a2c39c9a7e8.png)
可以这样处理

**Comment by tangtanglove** [comment]
如果模型里定义了关联关系，也可以用下面的方式：
![image](https://user-images.githubusercontent.com/60868863/146744554-9ea3d7e7-1877-4f03-8e43-93f5f01e31a0.png)

**Comment by tuowt** [comment]
感谢大佬，🙏
