### ISSUE TITLE
A bug about the map component and other questions

### ISSUE THREAD

**Issue by ShiveringPan** [quarkcms/quark-admin#28]
1. map Component  bug

![4V0E`A91I0}63M 5YDW_9OM](https://user-images.githubusercontent.com/25818289/147720057-a7a7d54a-9861-4683-9aab-6e94c805070a.png)

![A3`4{@58ZE4NP9`~ER~0VEN](https://user-images.githubusercontent.com/25818289/147719835-a5eda255-d2b2-4625-865d-4d33bbfaade2.png)
The first one is that the map component is displayed normally when editing the form
The second is that the map component shows the default value when editing the form

2. Need some examples 
![K2S@% XNZ)SX1(`V6 RD%NG](https://user-images.githubusercontent.com/25818289/147719873-c36bf4b0-4a22-4513-b687-93c35906c92f.png)
I don’t know how to create such an example like  Button click show Modal. Because there is only one function actions in the resource

thanks

**Comment by tangtanglove** [comment]
map example `Field::map($column[, $label])->style(['width'=>'100%','height'=>400])->position($longitude,$latitude);`

**Comment by tangtanglove** [comment]
[`Modal Action Demo`](https://www.quarkcms.com/quark-admin/actions.html#%E8%A1%8C%E4%B8%BA%E7%B1%BB%E5%9E%8B)
