### ISSUE TITLE
是否可以升一下laravel的版本呢，目前版本到laravel 9

### ISSUE THREAD

**Issue by kopalam** [quarkcms/quark-admin#33]
作者你好，请问是否可以升一下laravel的版本呢，目前版本到laravel 9

**Comment by kopalam** [comment]
我在 9 中使用composer require quarkcms/quark-admin
我的PHP版本为php 8.1.1 ,laravel版本为 9
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-permission[3.0, ..., 3.10.0] require php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
    - spatie/laravel-permission[3.10.1, ..., 3.17.0] require php ^7.2.5 -> your php version (8.1.1) does not satisfy that requirement.
    - spatie/laravel-permission[3.18.0, ..., v3.x-dev] require illuminate/auth ^5.8|^6.0|^7.0|^8.0 -> found illuminate/auth[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - quarkcms/quark-admin[v2.2.0, ..., v2.2.25] require spatie/laravel-permission ^3.0 -> satisfiable by spatie/laravel-permission[3.0, ..., v3.x-dev].
    - Root composer.json requires quarkcms/quark-admin ^2.2 -> satisfiable by quarkcms/quark-admin[v2.2.0, ..., v2.2.25].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require quarkcms/quark-admin:*" to figure out if any version is installable, or "composer require quarkcms/quark-admin:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by tangtanglove** [comment]
精力有限，请移步到quark-go吧
