### ISSUE TITLE
安装后，后台登陆成功后，直接报错，无法显示界面

### ISSUE THREAD

**Issue by fjn1019426010** [quarkcms/quark-admin#34]
安装后，后台登陆成功后，直接报错，无法显示界面
exception: "ErrorException"
file: "/www/wwwroot/qyou-sass/vendor/quarkcms/quark/src/Component/Layout/PageContainer.php"
line: 303
message: "Undefined index: title"
<img width="963" alt="image" src="https://github.com/quarkcms/quark-admin/assets/19318000/e465cd2f-b688-44c6-8e3c-a9c1e69a7c4e">

**Comment by tangtanglove** [comment]
推荐使用https://github.com/quarkcms/quark-go
