### ISSUE TITLE
请问有quark-admin开发的实例项目吗？

### ISSUE THREAD

**Issue by krvipsoft** [quarkcms/quark-admin#6]
近期有个项目需要用的ant design + laravel ,所以找到这个框架，很接近需求，但是不知道用起来容易上手吗？会使用自定义的功能。

**Comment by tangtanglove** [comment]
https://github.com/quarkcms/quark-cms，还有一些公司内部的系统。

**Comment by krvipsoft** [comment]
请问权限部分怎么添加和使用呢？现在只有同步按钮
添加角色后会报错！路由地址多了一个/
![image](https://user-images.githubusercontent.com/42866392/91782685-bfe4fb80-ec38-11ea-81d1-ee0842110f62.png)
还有添加角色后，编辑角色时没有对应的角色和权限关系
![image](https://user-images.githubusercontent.com/42866392/91782949-98426300-ec39-11ea-8023-6d31257d000c.png)
整体的样式和页面布局怎么修改呢？
请告知下，谢谢！

**Comment by tangtanglove** [comment]
404的问题需要更新一下依赖版本，使用最新的版本

**Comment by tangtanglove** [comment]
![image](https://user-images.githubusercontent.com/60868863/91783388-ab9e0000-ec32-11ea-835e-62ac2a0f5145.png)
第一步，先同步权限；
![image](https://user-images.githubusercontent.com/60868863/91783421-c6707480-ec32-11ea-9944-22f0993882c7.png)
第二部，给菜单绑定权限；
第三部，创建角色

**Comment by krvipsoft** [comment]
新增权限怎么操作呢？

**Comment by tangtanglove** [comment]
不用新增，直接点击同步就行；会自动读取路由，插入到权限表里。

**Comment by krvipsoft** [comment]
404的问题需要更新一下依赖版本，使用最新的版本
这个是执行composer update 吗

**Comment by tangtanglove** [comment]
是的

**Comment by krvipsoft** [comment]
整体的样式和页面布局怎么修改呢？

**Comment by tangtanglove** [comment]
样式和布局你可以自己编译quark-ui

**Comment by krvipsoft** [comment]
404 我执行了composer更新，但是还提示
![image](https://user-images.githubusercontent.com/42866392/91785377-389b8600-ec40-11ea-92e0-56a172c25755.png)
是路由多了一个斜杠

**Comment by tangtanglove** [comment]
嗯，那你可以改一下菜单链接

**Comment by krvipsoft** [comment]
菜单是对的，是添加或编辑完角色之后跳转时有个斜杠

**Comment by tangtanglove** [comment]
我这里没有此问题

**Comment by krvipsoft** [comment]
是底层包的问题RoleController.php
![image](https://user-images.githubusercontent.com/42866392/91786314-50740980-ec42-11ea-8bd2-4e1223a98699.png)

**Comment by krvipsoft** [comment]
看下是不是没有更新

**Comment by tangtanglove** [comment]
感谢，已修复，已发包

**Comment by krvipsoft** [comment]
quark-ui 布局能说下细节吗？比如修改为light风格

**Comment by tangtanglove** [comment]
https://preview.pro.ant.design/dashboard/analysis
![image](https://user-images.githubusercontent.com/60868863/91788364-99c25a00-ec3e-11ea-8bec-5249995f2870.png)
参考文档https://procomponents.ant.design/components/layout#settings

**Comment by krvipsoft** [comment]
这个是放到.umirc.ts里吗？
![image](https://user-images.githubusercontent.com/42866392/91790186-152a0880-ec4b-11ea-93d8-2e917d7f71d8.png)

**Comment by tangtanglove** [comment]
是的

**Comment by krvipsoft** [comment]
我重新编译后，还是dark风格，没有变呢？

**Comment by tangtanglove** [comment]
需要把public/admin下的文件删除，然后将你编译的文件复制进来

**Comment by krvipsoft** [comment]
还是没有变，你那边可以测试下吗？谢谢啦

**Comment by krvipsoft** [comment]
我把编译后的放到public/admin现在点不开了
![image](https://user-images.githubusercontent.com/42866392/91792745-3c83d400-ec51-11ea-9b0f-46014bf1897f.png)

**Comment by krvipsoft** [comment]
现在只能用你编译后的
